name: Push base language translations to Lokalise
on:
  workflow_dispatch:

permissions:
  contents: write
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v4.0.0
        with:
          api_token: 1f7d91b487831c7264c6643be0cb8d40162efea7
          project_id: 3939761469d33783c0acc1.91645315
          base_lang: en
          translations_path: |
            src/locales
          file_format: json
          file_ext: json
          flat_naming: true
          additional_params: >
            {
              "tag_inserted_key": true,
              "tag_updated_keys": false,
              "tags": ["need-translation"]
            }